---
apiVersion: v1
kind: Namespace
metadata:
  name: cni-tshoot

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: cni-tshoot
  labels:
    app: nginx
spec:
  replicas: 15
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: app
                operator: In
                values:
                - cni_troubleshooting
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      tolerations:
      - key: "purpose"
        operator: "Exists"
        effect: "NoSchedule"
